//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTEP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CTEPEntities : DbContext
    {
        public CTEPEntities()
            : base("name=CTEPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Academys> Academys { get; set; }
        public virtual DbSet<AccountInfo> AccountInfo { get; set; }
        public virtual DbSet<Assessment> Assessment { get; set; }
        public virtual DbSet<CommentTemplates> CommentTemplates { get; set; }
        public virtual DbSet<CourseTemplates> CourseTemplates { get; set; }
        public virtual DbSet<CTEPSysCofig> CTEPSysCofig { get; set; }
        public virtual DbSet<EvalutionForms> EvalutionForms { get; set; }
        public virtual DbSet<Grads> Grads { get; set; }
        public virtual DbSet<SchoolBandisTabs> SchoolBandisTabs { get; set; }
        public virtual DbSet<University> University { get; set; }
        public virtual DbSet<UserBandis> UserBandis { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserSetTabs> UserSetTabs { get; set; }
    }
}
