//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvalutionForms
    {
        public int id { get; set; }
        public Nullable<int> CreateId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string author { get; set; }
        public Nullable<double> score { get; set; }
        public Nullable<int> FormStatus { get; set; }
        public string title { get; set; }
        public string body { get; set; }
        public byte[] img { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> EStartTime { get; set; }
        public Nullable<System.DateTime> EEndTime { get; set; }
        public Nullable<int> Eweek { get; set; }
        public Nullable<int> BandiId { get; set; }
    }
}
